version: '3'
services:
  web:
    image: "nginx:latest"
    restart: unless-stopped
    volumes:
      - ./web/public:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
     - NGINX_HOST=markseymour.ca
     - NGINX_PORT=80
