version: '3'

services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "2300:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./.nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7-fpm
    volumes:
      - .:/usr/share/nginx/html
