version: '3'

services:
    www-markseymour-ca:
        build: '.'
        image: 'azuretan/markseymour.ca'
        container_name: 'web-nginx'
        restart: 'unless-stopped'
        ports:
            - '2300:8080'

networks:
  default:
    name: npm-net
    external: true
