version: '3'

services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./web/public:/usr/share/nginx/html
      - ./web/.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7-fpm
    volumes:
      - ./web/public:/usr/share/nginx/html
