version: '3'
services:
    frontend:
        restart: unless-stopped
        build:
          context: ./public
          dockerfile: ../Dockerfile
        ports:
            - 80:80/tcp
            - 443:443/tcp
        environment:
            - CERTBOT_EMAIL=mark.seymour.ns@gmail.com
