version: '3'

services:
    web:
        build: '.'
        image: 'azuretan/markseymour.ca'
        container_name: 'web-nginx'
        restart: 'unless-stopped'
        ports:
            - '8080:8080'
